@startuml

title __MODEL's Class Diagram__\n

  namespace com.netmart.netmartseller {
    namespace Model {
      class com.netmart.netmartseller.Model.Address {
          - city : String
          - houseArea : String
          - houseNo : String
          - postcode : String
          - state : String
          - street : String
          + Address()
          + Address()
          + getCity()
          + getHouseArea()
          + getHouseNo()
          + getPostcode()
          + getState()
          + getStreet()
          + setCity()
          + setHouseArea()
          + setHouseNo()
          + setPostcode()
          + setState()
          + setStreet()
      }
    }
  }
  

  namespace com.netmart.netmartseller {
    namespace Model {
      class com.example.netmart.Model.Cart {
          - amount : String
          - discount : String
          - name : String
          - pid : String
          - price : String
          + Cart()
          + Cart()
          + getAmount()
          + getDiscount()
          + getName()
          + getPid()
          + getPrice()
          + setAmount()
          + setDiscount()
          + setName()
          + setPid()
          + setPrice()
      }
    }
  }
  

  namespace com.netmart.netmartseller {
    namespace Model {
      class com.example.netmart.Model.Orders {
          - city : String
          - date : String
          - houseArea : String
          - houseNo : String
          - name : String
          - phone : String
          - postcode : String
          - received : String
          - sent : String
          - state : String
          - street : String
          - time : String
          - totalAmount : String
          - username : String
          + Orders()
          + Orders()
          + getCity()
          + getDate()
          + getHouseArea()
          + getHouseNo()
          + getName()
          + getPhone()
          + getPostcode()
          + getReceived()
          + getSent()
          + getState()
          + getStreet()
          + getTime()
          + getTotalAmount()
          + getUsername()
          + setCity()
          + setDate()
          + setHouseArea()
          + setHouseNo()
          + setName()
          + setPhone()
          + setPostcode()
          + setReceived()
          + setSent()
          + setState()
          + setStreet()
          + setTime()
          + setTotalAmount()
          + setUsername()
      }
    }
  }
  

  namespace com.netmart.netmartseller {
    namespace Model {
      class com.example.netmart.Model.Products {
          - category : String
          - date : String
          - description : String
          - image : String
          - name : String
          - nameLower : String
          - pid : String
          - price : String
          - time : String
          + Products()
          + Products()
          + getCategory()
          + getDate()
          + getDescription()
          + getImage()
          + getName()
          + getNameLower()
          + getPid()
          + getPrice()
          + getTime()
          + setCategory()
          + setDate()
          + setDescription()
          + setImage()
          + setName()
          + setNameLower()
          + setPid()
          + setPrice()
          + setTime()
      }
    }
  }
  

  namespace com.netmart.netmartseller {
    namespace Model {
      class com.example.netmart.Model.Users {
          - email : String
          - fullname : String
          - image : String
          - password : String
          - phone : String
          - username : String
          + Users()
          + Users()
          + getEmail()
          + getFullname()
          + getImage()
          + getPassword()
          + getPhone()
          + getUsername()
          + setEmail()
          + setFullname()
          + setImage()
          + setPassword()
          + setPhone()
          + setUsername()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
